spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/studytrack
spring.datasource.username=postgres
spring.datasource.password=passwort123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT secret key (for demonstration purposes only, use a secure key in production)
jwt.secret=7f1a9d2c8e5b3f4a6d1e9c2b8a7f3e5d9c1a4b6e8f2d7c5
jwt.expiration=3600000